# -*- coding: utf-8 -*-
"""1_study4_damage_part_classification_yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhewMJQ8msvuFoVOmgehsmHe57OWFMQ3
"""

### train시 1시간 정도 소모 됩니다. colab환경에서 아래를 browser의 console 에서 붙여 넣기가 필요할 수 있습니다.
### shift+cntr+i 로 browser console 열기
# https://github.com/chulminkw/DLCV/blob/master/data/util/colab_autoclick.js
'''
function ClickConnect(){
console.log("Working");
document.querySelector("colab-toolbar-button#connect").click()
}
setInterval(ClickConnect,60000)
'''

"""# step1. Colab 환경 설정 및 데이터 준비"

## 1-1. 라이브러리 설치 및 드라이브 마운트
"""

# 1. YOLOv8 라이브러리 설치
!pip install ultralytics -q

# 2. 구글 드라이브 마운트 (데이터셋을 드라이브에 올린 경우)
from google.colab import drive
drive.mount('/content/drive')

"""## 1-2. 데이터셋 압축 해제"""

import os
import shutil

# 1. 경로 설정
# 구글 드라이브에 업로드한 파일 경로 (파일명 확인 필수!)
drive_path = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION/balanced_dataset_split_polygon.zip"

# Colab 내부로 복사할 경로
local_zip_path = '/content/balanced_dataset_split_polygon.zip'
extract_path = '/content/dataset'

# 2. 파일 복사 (Drive -> Colab Local)
print(f"🚀 구글 드라이브에서 데이터 복사 중... ({drive_path} -> {local_zip_path})")
if not os.path.exists(drive_path):
    print("❌ 오류: 구글 드라이브에 파일이 없습니다. 경로를 확인해주세요.")
else:
    shutil.copy(drive_path, local_zip_path)
    print("✅ 복사 완료!")

    # 3. 압축 해제
    print(f"📂 압축 해제 중... (대상: {extract_path})")
    if not os.path.exists(extract_path):
        os.makedirs(extract_path)

    # 리눅스 명령어로 압축 해제 (파이썬보다 빠름, -q 옵션으로 로그 숨김 필수)
    # unzip이 없으면 !apt-get install unzip
    !unzip -q {local_zip_path} -d {extract_path}

    print("✅ 압축 해제 및 준비 완료!")

"""# Step 2: 데이터셋 검증 (현황 및 시각화)

## 2-1. 현황 파악
"""

import glob
import cv2
import matplotlib.pyplot as plt
import random
import numpy as np
from pathlib import Path
import yaml

# 데이터셋 루트 경로 (압축 해제된 폴더 내부로 지정)
# 주의: 압축 해제 시 폴더 구조에 따라 경로가 다를 수 있습니다. 확인 필요.
DATASET_ROOT = '/content/dataset/balanced_dataset_split_polygon'

# 1. 데이터 현황 파악 (개수 확인)
def check_data_status(root_dir):
    print(f"📊 데이터셋 현황 ({root_dir})")
    print("-" * 30)
    for split in ['train', 'val', 'test']:
        img_dir = os.path.join(root_dir, split, 'images')
        lbl_dir = os.path.join(root_dir, split, 'labels')

        num_imgs = len(glob.glob(os.path.join(img_dir, '*.*')))
        num_lbls = len(glob.glob(os.path.join(lbl_dir, '*.txt')))

        print(f"[{split.upper()}] Images: {num_imgs} | Labels: {num_lbls}")

        if num_imgs != num_lbls:
            print(f"  ⚠️ 경고: {split} 데이터의 이미지와 라벨 개수가 다릅니다!")

check_data_status(DATASET_ROOT)

import os
import glob
import pandas as pd

# 1. 설정 (데이터셋 경로)
DATASET_ROOT = '/content/dataset/balanced_dataset_split_polygon'

# 클래스 리스트 (제공해주신 순서)
class_names = [
    "Front fender(L)", "Rear bumper", "Front Wheel(R)", "Trunk lid", "Rocker panel(L)",
    "Front fender(R)", "Front bumper", "Bonnet", "Rear Wheel(R)", "Rear door(R)",
    "Front door(R)", "Head lights(R)", "Rear fender(R)", "Rear fender(L)", "Rocker panel(R)",
    "Rear lamp(L)", "Side mirror(R)", "Rear Wheel(L)", "Rear door(L)", "Side mirror(L)",
    "Head lights(L)", "Front Wheel(L)", "Front door(L)", "Rear lamp(R)", "Windshield",
    "Roof", "Undercarriage", "Rear windshield", "C pillar(L)", "A pillar(L)",
    "C pillar(R)", "A pillar(R)"
]

# 2. 데이터 집계 (Train / Val / Test 각각 카운팅)
# 딕셔너리 구조: { '부위명': {'train': 0, 'val': 0, 'test': 0}, ... }
data_counts = {name: {'train': 0, 'val': 0, 'test': 0} for name in class_names}
splits = ['train', 'val', 'test']

print("🔄 데이터 전수 조사 중 (Train/Val/Test)...")

for split in splits:
    # 해당 split 폴더의 모든 txt 파일 탐색
    label_files = glob.glob(os.path.join(DATASET_ROOT, split, 'labels', '*.txt'))

    for txt_file in label_files:
        try:
            with open(txt_file, 'r') as f:
                lines = f.readlines()
                for line in lines:
                    parts = line.strip().split()
                    if not parts: continue

                    # YOLO format: [class_id] [coords...]
                    try:
                        class_id = int(parts[0])
                        if 0 <= class_id < len(class_names):
                            name = class_names[class_id]
                            data_counts[name][split] += 1
                    except ValueError:
                        continue
        except Exception:
            pass # 파일 읽기 에러는 무시

# 3. 데이터프레임 변환 및 Total/Ratio 계산
rows = []
for name, counts in data_counts.items():
    total_per_class = counts['train'] + counts['val'] + counts['test']
    rows.append({
        'Class Name': name,
        'Train': counts['train'],
        'Val': counts['val'],
        'Test': counts['test'],
        'Total': total_per_class
    })

df = pd.DataFrame(rows)

# 전체 데이터 총합 (Grand Total) 계산
grand_total = df['Total'].sum()

# 비율(Ratio) 계산: (해당 부위 Total / 전체 Grand Total) * 100
df['Ratio (%)'] = (df['Total'] / grand_total * 100) if grand_total > 0 else 0

# Total 기준 내림차순 정렬
df = df.sort_values(by='Total', ascending=False).reset_index(drop=True)

# 4. 결과 출력 (Markdown Table 형식)
print("\n" + "="*20 + " [COPY FOR README.md] " + "="*20)
print(f"\n### 📊 차량 부위별 데이터셋 상세 분포 (총 {grand_total:,}개 객체)")
print(f"\n| 순위 | 부위 명칭 (Class Name) | Train | Val | Test | Total | Ratio (%) |")
print("| :---: | :--- | :---: | :---: | :---: | :---: | :---: |")

for i, row in df.iterrows():
    # 천 단위 콤마(,) 포맷팅 적용
    print(f"| {i+1} | {row['Class Name']} | {row['Train']:,} | {row['Val']:,} | {row['Test']:,} | {row['Total']:,} | {row['Ratio (%)']:.2f}% |")

print("\n" + "="*60)
print(f"✅ 분석 완료. 위 표를 복사해서 사용하세요.")

"""## 2-2. segmentation 학습"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
import random
import glob

# 1. 설정: 데이터셋 경로
DATASET_ROOT = '/content/dataset/balanced_dataset_split_polygon'
classes_list = [
    "Front fender(L)", "Rear bumper", "Front Wheel(R)", "Trunk lid", "Rocker panel(L)",
    "Front fender(R)", "Front bumper", "Bonnet", "Rear Wheel(R)", "Rear door(R)",
    "Front door(R)", "Head lights(R)", "Rear fender(R)", "Rear fender(L)", "Rocker panel(R)",
    "Rear lamp(L)", "Side mirror(R)", "Rear Wheel(L)", "Rear door(L)", "Side mirror(L)",
    "Head lights(L)", "Front Wheel(L)", "Front door(L)", "Rear lamp(R)", "Windshield",
    "Roof", "Undercarriage", "Rear windshield", "C pillar(L)", "A pillar(L)",
    "C pillar(R)", "A pillar(R)"
]

# 2. 샘플 이미지 및 라벨 로드 함수
def get_random_sample(root_dir, split='train'):
    img_dir = os.path.join(root_dir, split, 'images')
    lbl_dir = os.path.join(root_dir, split, 'labels')

    img_files = glob.glob(os.path.join(img_dir, '*.*'))
    if not img_files:
        raise FileNotFoundError(f"이미지를 찾을 수 없습니다: {img_dir}")

    # 랜덤 선택
    img_path = random.choice(img_files)
    file_name = os.path.splitext(os.path.basename(img_path))[0]
    lbl_path = os.path.join(lbl_dir, file_name + '.txt')

    return img_path, lbl_path

# 3. 데이터 파싱 및 시각화 준비
img_path, lbl_path = get_random_sample(DATASET_ROOT, split='train')

# 이미지 로드
img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
h, w, c = img.shape

# 라벨 파싱
polygons = [] # 다각형 좌표 리스트
bboxes = []   # 바운딩 박스 리스트
class_ids = []

if os.path.exists(lbl_path):
    with open(lbl_path, 'r') as f:
        lines = f.readlines()
        for line in lines:
            parts = list(map(float, line.strip().split()))
            cls_id = int(parts[0])
            coords = parts[1:]

            # 정규화된 좌표(0~1)를 픽셀 좌표(px)로 변환
            pts = []
            for i in range(0, len(coords), 2):
                px = int(coords[i] * w)
                py = int(coords[i+1] * h)
                pts.append([px, py])

            pts = np.array(pts, np.int32)
            polygons.append(pts)
            class_ids.append(cls_id)

            # Polygon에서 Bounding Box 추출 (min x, min y, max x, max y)
            x_min, y_min = np.min(pts, axis=0)
            x_max, y_max = np.max(pts, axis=0)
            bboxes.append([x_min, y_min, x_max, y_max])

# 4. 시각화 생성 (4가지 관점)

# [View 1] Vector Visualization (Polygon + BBox)
vis_vector = img.copy()
for pts, box, cid in zip(polygons, bboxes, class_ids):
    # Polygon 그리기 (선)
    cv2.polylines(vis_vector, [pts], isClosed=True, color=(0, 255, 0), thickness=2)
    # Bounding Box 그리기 (점선 흉내)
    cv2.rectangle(vis_vector, (box[0], box[1]), (box[2], box[3]), (255, 0, 0), 1)
    # 텍스트
    cv2.putText(vis_vector, classes_list[cid], (box[0], box[1]-5),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)

# [View 2] Binary Mask (Machine's View)
# 검은 배경에 흰색으로 채워진 영역 (학습의 정답지)
mask_img = np.zeros((h, w), dtype=np.uint8)
for pts in polygons:
    cv2.fillPoly(mask_img, [pts], 255)

# [View 3] Instance Overlay (Final Goal)
vis_overlay = img.copy()
for pts, cid in zip(polygons, class_ids):
    # 색상 랜덤 생성
    color = np.random.randint(0, 255, (3,), dtype=np.uint8).tolist()

    # 1. 마스크 영역 생성
    overlay = vis_overlay.copy()
    cv2.fillPoly(overlay, [pts], color)

    # 2. 원본과 블렌딩 (투명도 0.5)
    cv2.addWeighted(overlay, 0.5, vis_overlay, 0.5, 0, vis_overlay)

    # 3. 외곽선 강조
    cv2.polylines(vis_overlay, [pts], True, color, 2)

# 5. Plotting
fig, axes = plt.subplots(1, 4, figsize=(24, 6))
titles = ["1. Original Image", "2. Vector Label (Point & Box)", "3. Binary Mask (Machine View)", "4. Instance Overlay"]
images = [img, vis_vector, mask_img, vis_overlay]

for ax, img_show, title in zip(axes, images, titles):
    if len(img_show.shape) == 2: # Gray scale (Mask)
        ax.imshow(img_show, cmap='gray')
    else:
        ax.imshow(img_show)
    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.axis('off')

plt.suptitle(f"Segmentation Theory: From Coordinates to Pixels\nFile: {os.path.basename(img_path)}", fontsize=16)
plt.tight_layout()
plt.show()

"""## ※ Segmentation 기초 학습: Polygon to Mask
 1. Original: 원본 이미지
 2. Vector (Polygon & BBox): 라벨링 툴에서 우리가 찍는 점(Point)과 이를 감싸는 박스.
    - 초록색 선이 라벨링 데이터(Polygon)
    - 파란색 박스는 Polygon의 최소/최대 좌표로 계산된 Bounding Box
    - Polygon은 오직 '차체 부위'만 감싸고 있어 Segmentation이 더 정밀한 이유
 3. Raster (Binary Mask): (핵심) 점들이 연결되어 만들어진 '면적'. 컴퓨터는 이 0(배경)과 1(객체)의 픽셀 지도를 학습
    - 컴퓨터는 이미지를 숫자의 배열
    - Segmentation 모델(YOLOv8-seg)은 최종적으로 이 흑백 이미지(Mask)를 정답지로 삼아, 입력 이미지를 보며 이 모양을 똑같이 그려내도록 학습
    - 이 과정에서 cv2.fillPoly 같은 함수가 좌표를 픽셀 면적으로 바꿔주는 역할
 4. Overlay: 원본 위에 마스크를 씌운 결과.
"""

import numpy as np
import matplotlib.pyplot as plt

# 1. 가상의 12x12 마스크 생성 (0으로 채워진 검은 배경)
grid_size = 12
mask = np.zeros((grid_size, grid_size), dtype=np.uint8)

# 2. 십자가 모양 그리기 (1로 채워서 객체 표시)
# (실제로는 255를 쓰지만, 여기선 보기 편하게 1로 표시)
mask[3:9, 5:7] = 1  # 세로 막대
mask[5:7, 3:9] = 1  # 가로 막대

# 3. 시각화 (이미지와 숫자를 겹쳐서 보여줌)
plt.figure(figsize=(8, 8))
plt.imshow(mask, cmap='gray') # 0은 검정, 1은 흰색으로 출력

# 각 픽셀 위에 실제 숫자(0 또는 1) 적기
for i in range(grid_size):
    for j in range(grid_size):
        value = mask[i, j]
        # 글자색: 배경이 검정이면 흰색, 배경이 흰색이면 검정색
        text_color = 'white' if value == 0 else 'black'
        plt.text(j, i, str(value), ha='center', va='center',
                 color=text_color, fontsize=12, fontweight='bold')

plt.title("Computer's View: Binary Mask is just a Matrix", fontsize=15)
plt.axis('off') # 축 숨기기
plt.tight_layout()
plt.show()

"""## 2-3. 이미지 시각화"""

import os
import glob
import random
import cv2
import numpy as np
import matplotlib.pyplot as plt

# 2. Polygon 시각화 검증 (클래스명 표시 수정 & 투명도 50%)
def visualize_polygon_sample(root_dir, split='train', num_samples=6):
    img_dir = os.path.join(root_dir, split, 'images')
    lbl_dir = os.path.join(root_dir, split, 'labels')

    # 1. 클래스 리스트 직접 정의 (파일 읽기 오류 방지)
    class_names = [
        "Front fender(L)", "Rear bumper", "Front Wheel(R)", "Trunk lid", "Rocker panel(L)",
        "Front fender(R)", "Front bumper", "Bonnet", "Rear Wheel(R)", "Rear door(R)",
        "Front door(R)", "Head lights(R)", "Rear fender(R)", "Rear fender(L)", "Rocker panel(R)",
        "Rear lamp(L)", "Side mirror(R)", "Rear Wheel(L)", "Rear door(L)", "Side mirror(L)",
        "Head lights(L)", "Front Wheel(L)", "Front door(L)", "Rear lamp(R)", "Windshield",
        "Roof", "Undercarriage", "Rear windshield", "C pillar(L)", "A pillar(L)",
        "C pillar(R)", "A pillar(R)"
    ]

    # 이미지 파일 리스트
    img_files = glob.glob(os.path.join(img_dir, '*.*'))
    if not img_files:
        print("❌ 이미지를 찾을 수 없습니다.")
        return

    # 샘플 랜덤 추출
    num_samples = min(num_samples, len(img_files))
    samples = random.sample(img_files, num_samples)

    plt.figure(figsize=(15, 10))

    for i, img_path in enumerate(samples):
        # 이미지 로드
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        h, w, _ = img.shape

        # 라벨 로드
        basename = os.path.splitext(os.path.basename(img_path))[0]
        lbl_path = os.path.join(lbl_dir, basename + '.txt')

        if os.path.exists(lbl_path):
            with open(lbl_path, 'r') as f:
                lines = f.readlines()

            for line in lines:
                parts = list(map(float, line.strip().split()))
                cls_id = int(parts[0])
                coords = parts[1:]

                # Polygon 좌표 복원
                points = []
                for j in range(0, len(coords), 2):
                    px = int(coords[j] * w)
                    py = int(coords[j+1] * h)
                    points.append([px, py])

                points = np.array(points, np.int32)
                points = points.reshape((-1, 1, 2))

                # 색상 설정
                color = plt.cm.tab10(cls_id % 10)
                color = tuple(int(c*255) for c in color[:3])

                # --- 투명도 50% 적용 ---
                overlay = img.copy()
                cv2.fillPoly(overlay, [points], color=color, lineType=cv2.LINE_AA)
                cv2.addWeighted(overlay, 0.5, img, 0.5, 0, img)
                cv2.polylines(img, [points], True, color, 2) # 외곽선
                # ---------------------

                # 텍스트 표시 수정: "클래스명 (ID)"
                if 0 <= cls_id < len(class_names):
                    name = class_names[cls_id]
                    label_text = f"{name} ({cls_id})"
                else:
                    label_text = f"ID: {cls_id}"

                # 텍스트 배경 (가독성 향상)
                text_size, _ = cv2.getTextSize(label_text, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
                text_x, text_y = points[0][0][0], points[0][0][1] - 10
                cv2.rectangle(img, (text_x, text_y - text_size[1] - 5), (text_x + text_size[0], text_y + 5), color, -1)

                # 텍스트 쓰기
                cv2.putText(img, label_text, (text_x, text_y),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1, cv2.LINE_AA)

        plt.subplot(2, 3, i+1)
        plt.imshow(img)
        plt.axis('off')
        plt.title(basename, fontsize=10)

    plt.tight_layout()
    plt.show()

# 실행
print("\n🔍 샘플 데이터 시각화 (Class Name + 50% Opacity)")
visualize_polygon_sample(DATASET_ROOT, split='train')



"""# Step 3: 학습 구성 (Training Configuration)

## 3-1. data.yaml 파일 생성
"""

DATASET_ROOT

import yaml

# 클래스 개수 및 이름 로드 (자동화)
classes_path = os.path.join(DATASET_ROOT, '/content/dataset/balanced_dataset_split_polygon/train/labels/classes.txt') # train 폴더 내부에 있을 수도 있음
with open(classes_path, 'r') as f:
    class_names = [line.strip() for line in f.readlines()]

# yaml 데이터 생성
data_config = {
    'path': DATASET_ROOT,  # 데이터셋 루트 경로
    'train': 'train/images',
    'val': 'val/images',
    'test': 'test/images',
    'names': {i: name for i, name in enumerate(class_names)}
}


# yaml 파일 저장
yaml_path = '/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION/car_parts_seg.yaml'
with open(yaml_path, 'w') as f:
    yaml.dump(data_config, f, sort_keys=False)

print(f"✅ 설정 파일 생성 완료: {yaml_path}")
print(f"🏷️  클래스 수: {len(class_names)}")

"""## 3-2. 모델 학습 시작 <주의>
 - Task: segment (Instance Segmentation) * Model: yolov8x-seg.pt (가장 성능이 좋은 모델 사용 권장)

 - Epochs: 50
"""

PROJECT_ROOT = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION"
SAVE_DIR = os.path.join(PROJECT_ROOT, "FINE_TUNING_MODEL")
yaml_path = '/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION/car_parts_seg.yaml'

from ultralytics import YOLO

# 1. 모델 로드 (Segmentation 전용 모델)
model = YOLO('yolov8x-seg.pt')

# 2. 학습 실행
model.train(
    data=yaml_path,  # 위에서 만든 yaml 경로
    epochs=50,          # 학습 반복 횟수
    imgsz=640,          # 이미지 크기
    batch=16,           # 메모리(VRAM)에 따라 조절 (T4: 8~16, A100: 32~)
    patience=10,        # 조기 종료 설정
    name='yolov8x_car_parts_seg', # 프로젝트 이름
    project=SAVE_DIR, # 결과 저장 경로 (드라이브 권장)
    exist_ok=True
)

"""# Step 4: 학습 결과 확인"""

import os
import glob
import random
from ultralytics import YOLO
from IPython.display import Image, display

# =========================================================
# ⚙️ 설정: 학습 코드와 동일한 경로 변수 활용
# =========================================================
# 학습 코드에서 정의된 SAVE_DIR가 메모리에 있다고 가정합니다.
# 만약 없다면 아래 줄 주석 해제 후 직접 입력
# SAVE_DIR = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION/FINE_TUNING_MODEL"

# 데이터셋 압축 해제 경로 (Colab 로컬 경로)
# 앞 단계에서 unzip한 경로와 일치해야 합니다.


PROJECT_ROOT = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION"
SAVE_DIR = os.path.join(PROJECT_ROOT, "FINE_TUNING_MODEL")
yaml_path = '/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION/car_parts_seg.yaml'

if 'DATASET_ROOT' not in locals():
    DATASET_ROOT = '/content/dataset/balanced_dataset_split_polygon'

# 1. 학습된 Best 모델 로드
project_name = 'yolov8x_car_parts_seg'
best_model_path = os.path.join(SAVE_DIR, project_name, 'weights', 'best.pt')

print(f"🔄 모델 로드 중: {best_model_path}")
if not os.path.exists(best_model_path):
    print("❌ 모델 파일이 아직 생성되지 않았거나 경로가 틀렸습니다. 학습이 완료되었는지 확인하세요.")
else:
    model = YOLO(best_model_path)

    # 2. Validation 셋에서 랜덤으로 5장만 샘플링
    val_img_dir = os.path.join(DATASET_ROOT, 'val', 'images')
    all_val_imgs = glob.glob(os.path.join(val_img_dir, '*.jpg')) + glob.glob(os.path.join(val_img_dir, '*.png'))

    if len(all_val_imgs) > 0:
        # 5장 샘플링 (전체를 다 돌리면 너무 오래 걸림)
        test_samples = random.sample(all_val_imgs, min(5, len(all_val_imgs)))
        print(f"🧪 테스트 대상: {len(test_samples)}장 (Random Sampling)")

        # 3. 추론 실행
        results = model.predict(
            source=test_samples,       # 리스트로 전달하면 해당 파일만 추론
            conf=0.25,
            save=True,
            project='/content/inference_result', # 결과는 Colab 임시 공간에 저장 (빠름)
            name='val_test',
            exist_ok=True
        )

        # 4. 결과 이미지 출력
        print("\n🖼️ 추론 결과 확인 (상위 3장)")
        output_dir = '/content/inference_result/val_test'
        result_imgs = glob.glob(os.path.join(output_dir, '*.jpg')) + glob.glob(os.path.join(output_dir, '*.png'))

        for img_path in result_imgs[:3]:
            display(Image(filename=img_path, width=600))
            print(f"Source: {os.path.basename(img_path)}")
    else:
        print(f"❌ 검증 이미지를 찾을 수 없습니다: {val_img_dir}")



"""# Step 5. 모델 성능 테스트

## 5-1. mAP
 - 개별 객체를 하나하나 얼마나 잘 찾고 모양을 땄는지 보는 지표.
 - Instance Segmentation(객체 개별 분리) 모델의 표준 평가지표. "얼마나 정확한 위치에, 얼마나 정확한 클래스로, 얼마나 빈틈없이 찾았는가"를 종합적으로 평가
    - Box mAP: 물체의 위치(네모 박스)를 얼마나 잘 찾았는가?
    - Mask mAP: 물체의 모양(폴리곤/마스크)을 얼마나 정확하게 땄는가? (YOLO Seg의 핵심)
 - 세부 기준:
    - mAP@50: 정답과 50%만 겹쳐도 "맞았다"고 쳐줄 때의 점수. (탐지율 확인용)
    - mAP@50-95: 50%부터 95%까지 엄격하게 평가한 평균 점수. (정밀도 확인용, 진짜 실력)
"""

import os
from ultralytics import YOLO
import pandas as pd
import datetime

# ==========================================
# 1. 설정 (경로 수정 필요)
# ==========================================
# 학습 때 사용한 데이터 설정 파일 (.yaml) 경로
#DATA_YAML_PATH = '/content/dataset/balanced_dataset_split_polygon/data.yaml'
DATA_YAML_PATH = '/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION/car_parts_seg.yaml'


# 학습된 모델 가중치 경로
PROJECT_ROOT = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION"
BEST_MODEL_PATH = os.path.join(PROJECT_ROOT, "FINE_TUNING_MODEL", "yolov8x_car_parts_seg", "weights", "best.pt")

# ==========================================
# 2. 공식 평가 수행 함수
# ==========================================
def run_standard_evaluation(model_path, data_yaml):
    print(f"🚀 공식 평가 프로세스 시작... (Model: {os.path.basename(model_path)})")

    # 모델 로드
    model = YOLO(model_path)

    # Ultralytics 내장 검증 실행 (COCO mAP 표준 계산)
    # split='test'는 data.yaml에 test 경로가 정의되어 있어야 함. 없다면 'val' 사용
    metrics = model.val(data=data_yaml, split='test', verbose=True, save_json=True)

    return metrics, model.names

# ==========================================
# 3. 결과 리포트 생성 함수
# ==========================================
def generate_evaluation_report(metrics, class_names):
    print("\n📊 평가 결과 집계 중...")

    # --- A. 전체 요약 (Overall) ---
    # Box(감지)와 Mask(세그멘테이션) 성능 분리
    summary_data = {
        "Metric": ["Precision (P)", "Recall (R)", "mAP@50", "mAP@50-95"],
        "Box (Detection)": [
            round(metrics.box.mp, 3),
            round(metrics.box.mr, 3),
            round(metrics.box.map50, 3),
            round(metrics.box.map, 3) # mAP@50-95
        ],
        "Mask (Segmentation)": [
            round(metrics.seg.mp, 3),
            round(metrics.seg.mr, 3),
            round(metrics.seg.map50, 3),
            round(metrics.seg.map, 3) # mAP@50-95
        ]
    }
    df_summary = pd.DataFrame(summary_data)

    # --- B. 클래스별 상세 성능 (Per-Class Mask mAP) ---
    # metrics.seg.maps에는 클래스 인덱스 순서대로 mAP50-95가 들어있음
    class_perf = []
    for i, ap in enumerate(metrics.seg.maps):
        name = class_names[i]
        class_perf.append({"Class": name, "Mask mAP@50-95": round(ap, 3)})

    df_class = pd.DataFrame(class_perf).sort_values(by="Mask mAP@50-95", ascending=False)

    # --- C. 리포트 작성 (Markdown) ---
    report = f"""
# 🏅 YOLO Segmentation 공식 성능 평가 리포트

**분석 일시**: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**모델**: {os.path.basename(BEST_MODEL_PATH)}

## 1. 종합 성능 평가 (Global Summary)
COCO Standard Metrics 기준 평가 결과입니다.
- **Box**: 물체 위치(네모)를 얼마나 잘 찾는가?
- **Mask**: 물체 모양(폴리곤)을 얼마나 잘 따는가? **(핵심 지표)**

{df_summary.to_markdown(index=False)}

> **해석 가이드**:
> - **mAP@50**: 0.8 이상이면 실무 적용 가능 수준.
> - **mAP@50-95**: 0.4 이상이면 양호, 0.6 이상이면 매우 우수함.

## 2. 클래스별 세그멘테이션 성능 (Class-wise Mask Performance)
어떤 클래스를 잘 찾고, 어떤 클래스에서 성능이 떨어지는지 확인하세요.

{df_class.to_markdown(index=False)}
"""
    return report

# ==========================================
# 4. 실행
# ==========================================
if __name__ == "__main__":
    try:
        # 1. 평가 실행
        metrics, class_names = run_standard_evaluation(BEST_MODEL_PATH, DATA_YAML_PATH)

        # 2. 리포트 생성
        final_report = generate_evaluation_report(metrics, class_names)

        # 3. 출력 및 저장
        print("\n" + "="*50)
        print(final_report)
        print("="*50)

        with open("OFFICIAL_EVALUATION_REPORT.md", "w", encoding="utf-8") as f:
            f.write(final_report)
        print("✅ 'OFFICIAL_EVALUATION_REPORT.md' 저장 완료")

    except Exception as e:
        print(f"❌ 오류 발생: {e}")
        print("Tip: data.yaml 경로가 정확한지, 'test' 데이터셋 경로가 yaml에 정의되어 있는지 확인하세요.")

"""## 5-2. mIoU
 - 개수 상관없이 전체 색칠 공부(면적)를 얼마나 잘했는지 보는 지표
 - Semantic Segmentation(픽셀 단위 분류) 모델에서 사용하는 지표
 - 개별 객체(차1, 차2)를 구분하지 않고, 전체 이미지에서 "정답 픽셀과 예측 픽셀이 얼마나 겹치는지" 면적 비율만 비교
 - 계산 방식: (교집합 면적) ÷ (합집합 면적)
 - 특징:
    - 객체가 100개든 1개든 상관없이, 전체 픽셀 덩어리의 일치도만 봅니다.
    - YOLO 모델로 mIoU를 계산하려면, YOLO가 찾은 개별 객체들을 하나의 맵으로 합치는(Merge) 과정이 필요

### 📋 YOLO VS Unet 상세 비교표

| 비교 항목 | YOLO (Instance Seg) | U-Net (Semantic Seg) | 💡 차량 파손 탐지 적용 시 (분석) |
| :--- | :--- | :--- | :--- |
| **객체 분리** | **가능 (O)** <br> (개별 객체로 인식) | **불가능 (X)** <br> (하나의 덩어리로 인식) | **🏆 YOLO 승** <br> 수리비 견적 산출 시 파손의 **'건수(Count)'** 파악이 핵심임 |
| **속도** | **매우 빠름** <br> (Real-time 가능) | **느림** <br> (무거운 구조) | **🏆 YOLO 승** <br> 사용자가 사진을 촬영하고 **즉시 결과**를 확인해야 하는 UX에 적합 |
| **복합 손상** | **구분 가능** <br> (예: 찌그러짐 위에 긁힘) | **구분 불가** <br> (겹치면 하나의 '손상') | **🏆 YOLO 승** <br> 여러 유형의 손상이 중첩된 경우 각각을 분리해내기에 유리함 |
| **데이터셋** | **Polygon 라벨링** <br> (점 찍기 방식) | **Mask 라벨링** <br> (픽셀 색칠 방식) | **🏆 YOLO 승** <br> Polygon 방식이 데이터 구축 속도가 빠르고 비용이 저렴함 |
| **경계면 정밀도** | **좋음** <br> (최신 버전에서 크게 향상) | **매우 좋음** <br> (픽셀 단위 완벽) | **✋ U-Net 우세** <br> 0.1mm 오차 없는 초정밀 면적 계산이 필요한 연구용이라면 U-Net이 유리 |

---

### ✅ 최종 선정: YOLO (Ultralytics YOLOv8-Seg)

**선정 이유:**
1. **견적 정확성**: '문짝 1개 파손'보다는 **'문짝에 긁힘 3건, 찌그러짐 1건'**과 같은 구체적인 정보 산출이 필수적입니다.
2. **서비스 사용성**: 모바일 환경에서의 빠른 추론 속도를 보장합니다.
3. **유지보수 용이성**: 데이터셋 구축(Labeling) 비용을 절감할 수 있으며, 최신 YOLO 모델의 Segmentation 성능은 상용 서비스에 충분한 수준입니다.
"""

import os
import cv2
import numpy as np
import glob
from ultralytics import YOLO
from sklearn.metrics import jaccard_score
from tqdm import tqdm
import torch

# ==========================================
# 1. 설정
# ==========================================
# 데이터셋 경로 (Images와 Labels)
TEST_IMG_DIR = '/content/dataset/balanced_dataset_split_polygon/test/images'
TEST_LABEL_DIR = '/content/dataset/balanced_dataset_split_polygon/test/labels'

# 모델 경로
MODEL_PATH = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION/FINE_TUNING_MODEL/yolov8x_car_parts_seg/weights/best.pt"

# 클래스 ID와 이름 (데이터셋에 맞게 수정 필요)
# 예: {0: 'Scratch', 1: 'Dent'}
# 현재는 모델에서 자동으로 불러오도록 설정됨

# ==========================================
# 2. 유틸리티 함수: 폴리곤 -> 바이너리 마스크 변환
# ==========================================
def polygon_to_mask(label_path, img_shape, class_id_target):
    """
    YOLO 라벨(.txt)을 읽어 특정 클래스에 대한 Binary Mask(0 or 1)를 생성합니다.
    Semantic Segmentation 비교를 위해 개별 객체를 구분하지 않고 모두 1로 합칩니다.
    """
    h, w = img_shape[:2]
    mask = np.zeros((h, w), dtype=np.uint8)

    if not os.path.exists(label_path):
        return mask

    with open(label_path, 'r') as f:
        lines = f.readlines()

    for line in lines:
        parts = line.strip().split()
        if len(parts) < 3: continue

        # 클래스 확인
        cls_id = int(parts[0]) if parts[0].isdigit() else -1

        # 해당 클래스만 마스크에 그림
        if cls_id == class_id_target:
            # 좌표 정규화 해제 (0~1 -> 0~w, 0~h)
            coords = np.array([float(x) for x in parts[1:]]).reshape(-1, 2)
            coords[:, 0] *= w
            coords[:, 1] *= h
            coords = coords.astype(np.int32)

            # 폴리곤 내부 채우기 (1로 설정)
            cv2.fillPoly(mask, [coords], 1)

    return mask

# ==========================================
# 3. mIoU 계산 메인 함수
# ==========================================
def calculate_semantic_miou(model_path, img_dir, label_dir):
    print(f"🚀 mIoU 계산 시작 (Model: {os.path.basename(model_path)})")

    model = YOLO(model_path)
    class_names = model.names
    num_classes = len(class_names)

    img_files = glob.glob(os.path.join(img_dir, '*.jpg')) + glob.glob(os.path.join(img_dir, '*.png'))
    img_files.sort()

    # 클래스별 IoU를 저장할 리스트
    # intersection_sum[class_id], union_sum[class_id]
    total_intersection = np.zeros(num_classes)
    total_union = np.zeros(num_classes)

    print(f"📂 총 {len(img_files)}장 이미지 분석 중...")

    for img_path in tqdm(img_files):
        # 1. 이미지 정보 읽기 (크기 필요)
        img = cv2.imread(img_path)
        if img is None: continue
        h, w = img.shape[:2]

        # 2. 라벨 파일 경로 찾기
        base_name = os.path.basename(img_path).rsplit('.', 1)[0]
        label_path = os.path.join(label_dir, base_name + '.txt')

        # 3. 모델 추론
        results = model.predict(img_path, conf=0.25, verbose=False, device=0 if torch.cuda.is_available() else 'cpu')
        result = results[0]

        # --- 클래스별로 반복하며 IoU 계산 ---
        for cls_id in range(num_classes):
            # A. Ground Truth Mask 생성 (Semantic: 모든 객체 합침)
            gt_mask = polygon_to_mask(label_path, (h, w), cls_id)

            # B. Prediction Mask 생성
            pred_mask = np.zeros((h, w), dtype=np.uint8)

            if result.masks is not None:
                # 현재 클래스에 해당하는 예측 마스크만 추출
                # result.boxes.cls는 감지된 객체들의 클래스 ID 리스트
                pred_cls_ids = result.boxes.cls.cpu().numpy().astype(int)

                # 마스크 데이터 (이미지 크기로 resize 필요할 수 있음. orig_shape 사용)
                # ultralytics의 masks.data는 GPU 텐서일 수 있음
                if hasattr(result.masks, 'data'):
                    # 마스크가 있는 경우
                    for i, det_cls in enumerate(pred_cls_ids):
                        if det_cls == cls_id:
                            # 개별 마스크 추출 및 리사이즈
                            # masks.data는 (N, H, W) 형태이나 원본 크기가 아닐 수 있음 -> scale_image 자동 처리됨?
                            # 안전하게 result.masks.xy (폴리곤 좌표)를 사용하여 다시 그리는 게 정확함

                            # 방식 1: 폴리곤 좌표로 다시 그리기 (가장 안전)
                            poly = result.masks.xy[i].astype(np.int32)
                            cv2.fillPoly(pred_mask, [poly], 1)

            # C. Intersection & Union 계산
            # flatten()으로 1차원 배열로 만든 뒤 계산
            inter = np.logical_and(gt_mask, pred_mask).sum()
            union = np.logical_or(gt_mask, pred_mask).sum()

            total_intersection[cls_id] += inter
            total_union[cls_id] += union

    # --- 최종 mIoU 계산 ---
    print("\n" + "="*50)
    print("📊 YOLO Segmentation -> Semantic mIoU 변환 결과")
    print("="*50)
    print(f"{'Class Name':<20} {'IoU':<10}")
    print("-" * 30)

    iou_list = []
    for cls_id in range(num_classes):
        if total_union[cls_id] == 0:
            iou = 0.0 # 정답도 없고 예측도 없었으면 0 (또는 데이터셋에 따라 NaN 처리)
            # 보통 정답이 아예 없는 클래스는 mIoU 평균에서 제외하기도 함
            print(f"{class_names[cls_id]:<20} {'N/A (No GT)':<10}")
            continue

        iou = total_intersection[cls_id] / total_union[cls_id]
        iou_list.append(iou)
        print(f"{class_names[cls_id]:<20} {iou:.4f}")

    miou = np.mean(iou_list) if iou_list else 0
    print("-" * 30)
    print(f"🏆 Final mIoU: {miou:.4f}")
    print("="*50)

    return miou

# 실행
if __name__ == "__main__":
    calculate_semantic_miou(MODEL_PATH, TEST_IMG_DIR, TEST_LABEL_DIR)

"""## 5-3. 속도"""

import os
import time
import torch
import numpy as np
import pandas as pd
from ultralytics import YOLO
from tqdm import tqdm

# ==========================================
# 1. 설정
# ==========================================
PROJECT_ROOT = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION"
BEST_MODEL_PATH = os.path.join(PROJECT_ROOT, "FINE_TUNING_MODEL", "yolov8x_car_parts_seg", "weights", "best.pt")

# 테스트할 이미지 폴더 (또는 단일 이미지 경로)
TEST_IMG_DIR = '/content/dataset/balanced_dataset_split_polygon/test/images'

# ==========================================
# 2. 속도 측정 함수
# ==========================================
def benchmark_speed(model_path, img_dir, num_samples=100):
    # 장치 설정
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f"🚀 속도 측정 시작... (Device: {device.upper()})")
    print(f"   모델: {os.path.basename(model_path)}")

    # 모델 로드
    model = YOLO(model_path)

    # 이미지 파일 리스트 가져오기
    img_files = [os.path.join(img_dir, f) for f in os.listdir(img_dir) if f.endswith(('.jpg', '.png', '.jpeg'))]
    if len(img_files) > num_samples:
        img_files = img_files[:num_samples] # 너무 많으면 샘플링

    print(f"📂 분석 대상: {len(img_files)}장")

    # --- [중요] GPU 워밍업 (Warm-up) ---
    # 처음 실행 시 GPU 초기화 비용 때문에 느리게 측정되는 것을 방지
    print("🔥 GPU 워밍업 중... (초기 지연 제거)")
    dummy_input = np.zeros((640, 640, 3), dtype=np.uint8)
    for _ in range(10):
        model.predict(dummy_input, verbose=False, device=device)

    # --- 실제 측정 시작 ---
    print("⏱️ 정밀 측정 시작...")

    times = {
        'preprocess': [],
        'inference': [],
        'postprocess': []
    }

    total_start = time.time()

    for img_path in tqdm(img_files):
        # 추론 수행 (verbose=False로 설정해야 순수 속도 측정 용이)
        results = model.predict(img_path, verbose=False, device=device)
        result = results[0]

        # YOLOv8은 결과 객체 내부에 단계별 소요 시간(ms)을 가지고 있음
        # result.speed = {'preprocess': 2.1, 'inference': 10.5, 'postprocess': 1.2}
        times['preprocess'].append(result.speed['preprocess'])
        times['inference'].append(result.speed['inference'])
        times['postprocess'].append(result.speed['postprocess'])

    total_duration = time.time() - total_start

    # --- 결과 집계 ---
    avg_pre = np.mean(times['preprocess'])
    avg_inf = np.mean(times['inference'])
    avg_post = np.mean(times['postprocess'])
    avg_total_latency = avg_pre + avg_inf + avg_post

    # FPS 계산 (1000ms / 1장당 총 소요시간 ms)
    fps = 1000 / avg_total_latency

    return avg_pre, avg_inf, avg_post, avg_total_latency, fps, device

# ==========================================
# 3. 리포트 생성
# ==========================================
if __name__ == "__main__":
    pre, inf, post, total, fps, device = benchmark_speed(BEST_MODEL_PATH, TEST_IMG_DIR, num_samples=200)

    print("\n" + "="*50)
    print("🏎️ YOLOv8-Seg Inference Speed Benchmark")
    print("="*50)

    df = pd.DataFrame({
        "Stage": ["Pre-process", "Inference (Neural Net)", "Post-process (NMS/Mask)", "Total Latency"],
        "Time (ms)": [f"{pre:.2f} ms", f"{inf:.2f} ms", f"{post:.2f} ms", f"{total:.2f} ms"],
        "Ratio": [f"{pre/total*100:.1f}%", f"{inf/total*100:.1f}%", f"{post/total*100:.1f}%", "100%"]
    })

    print(f"Device Used: {device.upper()}")
    print("-" * 50)
    print(df.to_string(index=False))
    print("-" * 50)
    print(f"🚀 Final FPS: {fps:.2f} Frames/sec")
    print("="*50)

    # 성능 평가 가이드
    print("\n[성능 해석 가이드]")
    if fps >= 30:
        print("✅ Real-time (실시간) 가능: 동영상 처리에 아주 적합합니다.")
    elif fps >= 10:
        print("⚠️ Near Real-time: 사용자 경험(UX)에 무리 없으나 빠른 동영상은 버거울 수 있습니다.")
    else:
        print("❌ Offline Only: 실시간 처리는 어렵고, 서버에서 배치 작업으로 처리해야 합니다.")

"""## 5-3. Test Set 기반 정량 평가 (Box/Mask mAP)
 - mAP (mean Average Precision): 모델의 정밀도(Precision)와 재현율(Recall)을 종합한 지표
 - Box mAP: 객체의 위치를 얼마나 정확히 찾았는가? (Detection 성능)
 - Mask mAP: 객체의 **형태(픽셀)**를 얼마나 정확히 땄는가? (Segmentation 성능)
 - IoU (Intersection over Union): 예측 영역과 정답 영역의 겹치는 비율을 계산하여, IoU 0.5~0.95 구간의 평균을 계산
"""

import os
import glob
import pandas as pd
from ultralytics import YOLO

# ======================================================================================
# 1. 설정 (경로 확인)
# ======================================================================================
DATASET_ROOT = '/content/dataset/balanced_dataset_split_polygon'
YAML_PATH = '/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION/car_parts_seg.yaml'

# 학습된 모델 경로
PROJECT_ROOT = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION"
BEST_MODEL_PATH = os.path.join(PROJECT_ROOT, "FINE_TUNING_MODEL", "yolov8x_car_parts_seg", "weights", "best.pt")

class_names = [
    "Front fender(L)", "Rear bumper", "Front Wheel(R)", "Trunk lid", "Rocker panel(L)",
    "Front fender(R)", "Front bumper", "Bonnet", "Rear Wheel(R)", "Rear door(R)",
    "Front door(R)", "Head lights(R)", "Rear fender(R)", "Rear fender(L)", "Rocker panel(R)",
    "Rear lamp(L)", "Side mirror(R)", "Rear Wheel(L)", "Rear door(L)", "Side mirror(L)",
    "Head lights(L)", "Front Wheel(L)", "Front door(L)", "Rear lamp(R)", "Windshield",
    "Roof", "Undercarriage", "Rear windshield", "C pillar(L)", "A pillar(L)",
    "C pillar(R)", "A pillar(R)"
]

# ======================================================================================
# 2. 데이터 집계
# ======================================================================================
print("🔄 데이터 집계 및 모델 평가 진행 중...")

data_counts = {name: {'train': 0, 'val': 0, 'test': 0} for name in class_names}
for split in ['train', 'val', 'test']:
    files = glob.glob(os.path.join(DATASET_ROOT, split, 'labels', '*.txt'))
    for f_path in files:
        try:
            with open(f_path, 'r') as f:
                for line in f:
                    try:
                        cid = int(line.split()[0])
                        if 0 <= cid < len(class_names):
                            data_counts[class_names[cid]][split] += 1
                    except: continue
        except: continue

# ======================================================================================
# 3. 모델 평가 (Test Set)
# ======================================================================================
if os.path.exists(BEST_MODEL_PATH):
    model = YOLO(BEST_MODEL_PATH)
    metrics = model.val(data=YAML_PATH, split='test', verbose=False, plots=False)

    # 전체 mAP (50-95)
    box_map = metrics.box.map
    mask_map = metrics.seg.map

    # 클래스별 mAP
    per_class_map = metrics.seg.maps
else:
    print("⚠️ 모델 없음. 더미 데이터 사용")
    box_map, mask_map = 0.0, 0.0
    per_class_map = [0.0] * len(class_names)

# ======================================================================================
# 4. 리포트 생성
# ======================================================================================
rows = []
for i, name in enumerate(class_names):
    c = data_counts[name]
    total = sum(c.values())
    m_val = per_class_map[i] if i < len(per_class_map) else 0.0
    rows.append({
        'Class Name': name,
        'Train': c['train'], 'Val': c['val'], 'Test': c['test'], 'Total': total,
        'mAP': m_val
    })

df = pd.DataFrame(rows).sort_values('Total', ascending=False)

# ======================================================================================
# 5. README.md 출력
# ======================================================================================
print("\n" + "="*30 + " [COPY FOR README.md] " + "="*30)
print("\n### 📈 모델 성능 평가 및 데이터 분포")
print(f"- **평가 데이터셋**: Test Set")
print(f"- **전체 Box mAP(50-95)**: `{box_map:.4f}`")
print(f"- **전체 Mask mAP(50-95)**: `{mask_map:.4f}`")

print(f"\n#### 📊 클래스별 상세 현황")
print(f"| 순위 | 부위 명칭 (Class Name) | Train | Val | Test | Total | Test mAP |")
print("| :---: | :--- | :---: | :---: | :---: | :---: | :---: |")

for i, row in df.iterrows():
    print(f"| {i+1} | {row['Class Name']} | {row['Train']:,} | {row['Val']:,} | {row['Test']:,} | {row['Total']:,} | **{row['mAP']:.4f}** |")

print("\n" + "="*80)

"""
## 5-4.  데이터 수량 vs 성능 상관관계 분석
 - Data Hunger Theory: 딥러닝 모델의 성능은 일반적으로 데이터 양의 로그(Log) 스케일에 비례하여 증가
    - 데이터가 10배 늘어날 때 성능이 선형적으로 증가
 - 이 패턴에서 벗어나는 클래스(데이터는 많은데 성능이 낮거나, 데이터는 적은데 성능이 높은 경우)는 **이상점(Outlier)**으로 간주하여 별도 분석이 필요
 - 단순히 "전체 mAP가 낮다"고 판단하는 오류를 범하지 않으려면, **"데이터가 부족해서 낮은 것인가, 형태가 어려워서 낮은 것인가?"**를 구분
 - 데이터 수량(Log Scale)과 성능(mAP) 간의 상관관계를 분석하고, 통계적으로 **이상점(Outlier)**을 식별하여 시각화
 - 표준편차 +- 1.5 이론적으로 전체의 약 13%(32개 중 약 4개)
"""



import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from ultralytics import YOLO

# ======================================================================================
# 1. 환경 설정 (사용자 경로에 맞게 수정 필수)
# ======================================================================================
DATASET_ROOT = '/content/dataset/balanced_dataset_split_polygon'
YAML_PATH = '/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION/car_parts_seg.yaml'

# 학습된 모델 경로
PROJECT_ROOT = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION"
BEST_MODEL_PATH = os.path.join(PROJECT_ROOT, "FINE_TUNING_MODEL", "yolov8x_car_parts_seg", "weights", "best.pt")

class_names = [
    "Front fender(L)", "Rear bumper", "Front Wheel(R)", "Trunk lid", "Rocker panel(L)",
    "Front fender(R)", "Front bumper", "Bonnet", "Rear Wheel(R)", "Rear door(R)",
    "Front door(R)", "Head lights(R)", "Rear fender(R)", "Rear fender(L)", "Rocker panel(R)",
    "Rear lamp(L)", "Side mirror(R)", "Rear Wheel(L)", "Rear door(L)", "Side mirror(L)",
    "Head lights(L)", "Front Wheel(L)", "Front door(L)", "Rear lamp(R)", "Windshield",
    "Roof", "Undercarriage", "Rear windshield", "C pillar(L)", "A pillar(L)",
    "C pillar(R)", "A pillar(R)"
]

# ======================================================================================
# 2. 데이터 집계 & 모델 평가
# ======================================================================================
print("🔄 데이터 집계 및 모델 평가 진행 중...")

# (1) 데이터 개수 집계
data_counts = {name: {'train': 0, 'val': 0, 'test': 0} for name in class_names}
for split in ['train', 'val', 'test']:
    files = glob.glob(os.path.join(DATASET_ROOT, split, 'labels', '*.txt'))
    for f_path in files:
        try:
            with open(f_path, 'r') as f:
                for line in f:
                    try:
                        cid = int(line.split()[0])
                        if 0 <= cid < len(class_names):
                            data_counts[class_names[cid]][split] += 1
                    except: continue
        except: continue

# (2) Test mAP 측정
if os.path.exists(BEST_MODEL_PATH):
    model = YOLO(BEST_MODEL_PATH)
    metrics = model.val(data=YAML_PATH, split='test', verbose=False, plots=False)
    per_class_map = metrics.seg.maps
    box_map_all = metrics.box.map
    mask_map_all = metrics.seg.map
else:
    print("⚠️ 모델 파일 없음. 더미 데이터 사용")
    per_class_map = np.random.rand(len(class_names))
    box_map_all, mask_map_all = 0.0, 0.0

# (3) DataFrame 생성
rows = []
for i, name in enumerate(class_names):
    c = data_counts[name]
    total = sum(c.values())
    m_val = per_class_map[i] if i < len(per_class_map) else 0.0

    # 로그 스케일 분석용 (0이면 1로 보정)
    log_count = np.log10(c['train']) if c['train'] > 0 else 0

    rows.append({
        'Class Name': name,
        'Train': c['train'], 'Val': c['val'], 'Test': c['test'], 'Total': total,
        'Log Train': log_count,
        'mAP': m_val
    })

df = pd.DataFrame(rows).sort_values('Total', ascending=False)

# ======================================================================================
# 3. [Output 1] README.md 표 출력
# ======================================================================================
print("\n" + "="*30 + " [COPY FOR README.md] " + "="*30)
print(f"\n### 📈 모델 성능 평가 및 데이터 분포")
print(f"- **전체 Box mAP**: `{box_map_all:.4f}` / **Mask mAP**: `{mask_map_all:.4f}`")
print(f"\n#### 📊 클래스별 상세 현황")
print(f"| 순위 | 부위 명칭 (Class Name) | Train | Val | Test | Total | Test mAP |")
print("| :---: | :--- | :---: | :---: | :---: | :---: | :---: |")

for i, row in df.iterrows():
    print(f"| {i+1} | {row['Class Name']} | {row['Train']:,} | {row['Val']:,} | {row['Test']:,} | {row['Total']:,} | **{row['mAP']:.4f}** |")
print("\n" + "="*80)

# ======================================================================================
# 4. [Output 2] 산점도(Scatter Plot) 시각화 및 이상점 분석
# ======================================================================================
print("\n📊 [Data Hunger Theory 분석] 산점도 생성 중...")

# 분석 대상: 학습 데이터가 1개 이상인 클래스만
df_anal = df[df['Train'] > 0].copy()

# 회귀 분석 (Trend Line)
slope, intercept, r_value, _, _ = stats.linregress(df_anal['Log Train'], df_anal['mAP'])
df_anal['Predicted'] = slope * df_anal['Log Train'] + intercept
df_anal['Residual'] = df_anal['mAP'] - df_anal['Predicted']

# 이상점 판별 (표준편차 1.5배)
std_resid = df_anal['Residual'].std()
df_anal['Status'] = df_anal['Residual'].apply(
    lambda x: 'Hard Case (Low Perf)' if x < -1.5 * std_resid else
              ('High Efficiency (Good)' if x > 1.5 * std_resid else 'Normal')
)

# 그래프 그리기
plt.figure(figsize=(12, 7))
sns.set_style("whitegrid")

# (1) 산점도
sns.scatterplot(data=df_anal, x='Train', y='mAP', size='Train', sizes=(50, 600),
                hue='Status', palette={'Normal': 'gray', 'Hard Case (Low Perf)': 'red', 'High Efficiency (Good)': 'green'},
                alpha=0.7, edgecolor='black')

# (2) 회귀선
x_range = np.linspace(df_anal['Train'].min(), df_anal['Train'].max(), 100)
y_trend = slope * np.log10(x_range) + intercept
plt.plot(x_range, y_trend, 'b--', label=f'Trend Line (R={r_value:.2f})')

# (3) 텍스트 라벨 (이상점만)
for _, row in df_anal.iterrows():
    if row['Status'] != 'Normal':
        plt.text(row['Train'], row['mAP'], row['Class Name'], fontsize=9, fontweight='bold', ha='right')

plt.xscale('log')
plt.title(f'Data Quantity vs Performance Analysis (R={r_value:.2f})', fontsize=14)
plt.xlabel('Number of Training Samples (Log Scale)')
plt.ylabel('Test Mask mAP (50-95)')
plt.legend(loc='lower right')

plt.tight_layout()
plt.savefig('performance_correlation_plot.png')
plt.show()

print(f"✅ 그래프가 'performance_correlation_plot.png'로 저장되었습니다.")

"""## 5-5. 수량 평가
 - 수량 비교 (Quantity): 정답 개수 vs 예측 개수 차이 (예: 정답 100개인데 150개 찾았으면 "과탐지")
 - 점수 분포 (Quality): 모델이 얼마나 확신을 갖고 찾는지(0~100점)
 - 상태 판정: Over(과탐지), Under(미탐지), Missed(놓침), New Detect(오탐) 등으로 분류
"""

import os
import glob
import numpy as np
import pandas as pd
from ultralytics import YOLO
import torch
import gc
import time
from collections import Counter

# ==========================================
# 1. 환경 설정
# ==========================================
DATASET_ROOT = '/content/dataset/balanced_dataset_split_polygon'
PROJECT_ROOT = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION"
BEST_MODEL_PATH = os.path.join(PROJECT_ROOT, "FINE_TUNING_MODEL", "yolov8x_car_parts_seg", "weights", "best.pt")

TEST_IMG_DIR = os.path.join(DATASET_ROOT, 'test', 'images')
TEST_LABEL_DIR = os.path.join(DATASET_ROOT, 'test', 'labels')

# ==========================================
# 2. 원본(GT) 분석 함수
# ==========================================
def analyze_ground_truth(label_dir):
    print(f"📂 [1/3] 원본 데이터(Labels) 스캔 중...")

    if not os.path.exists(label_dir):
        print(f"⚠️ 경로 없음: {label_dir}")
        return Counter(), 0

    txt_files = glob.glob(os.path.join(label_dir, '*.txt'))
    gt_counter = Counter()
    total_gt = 0

    # 리스트 컴프리헨션으로 파일 읽기 속도 개선
    for txt in txt_files:
        with open(txt, 'r') as f:
            lines = [line.strip().split() for line in f if line.strip()]

        for parts in lines:
            if not parts: continue
            raw_class = parts[0]

            # 클래스 키 처리 (숫자 or 문자열)
            key = int(raw_class) if raw_class.isdigit() else raw_class
            gt_counter[key] += 1
            total_gt += 1

    print(f"   ✅ 원본 객체 수: {total_gt:,}개")
    return gt_counter, total_gt

# ==========================================
# 3. 모델 예측 분석 함수 (속도 개선)
# ==========================================
def analyze_predictions(model_path, img_dir):
    # 메모리 정리
    torch.cuda.empty_cache()
    gc.collect()

    # 장치 자동 설정 (GPU 있으면 사용, 없으면 CPU)
    device = '0' if torch.cuda.is_available() else 'cpu'
    print(f"🚀 [2/3] 모델 추론 시작... (Device: {device})")
    print(f"   (참고: CPU일 경우 yolov8x 모델은 매우 느릴 수 있습니다)")

    if not os.path.exists(model_path):
        print("❌ 모델 파일이 없습니다.")
        return Counter(), [], 0, {}

    model = YOLO(model_path)
    class_names_map = model.names

    # ⚡ 속도 최적화 설정
    # stream=True: 메모리 절약 (대용량 처리에 필수)
    # verbose=False: 불필요한 출력 제거
    # conf=0.01: 분포 확인용 낮은 임계값
    results = model.predict(source=img_dir, conf=0.01, verbose=False, stream=True, device=device)

    pred_counter = Counter()
    all_scores = []

    start_time = time.time()
    count = 0

    # 결과 처리 루프
    for result in results:
        count += 1
        if result.boxes is None: continue

        # CPU로 데이터 이동 후 Numpy 변환 (속도 향상)
        cls_ids = result.boxes.cls.cpu().numpy().astype(int)
        scores = result.boxes.conf.cpu().numpy()

        # 배치 단위 카운팅 (루프 최소화)
        if len(cls_ids) > 0:
            pred_counter.update(cls_ids)
            all_scores.extend(scores)

        # 진행 상황 로그 (너무 자주 출력하면 느려지므로 100장 단위)
        if count % 100 == 0:
            elapsed = time.time() - start_time
            print(f"   -> {count}장 처리 중... ({elapsed:.1f}초)")

    total_pred = len(all_scores)
    print(f"   ✅ 예측 완료: 총 {total_pred:,}개 객체 탐지")

    return pred_counter, all_scores, total_pred, class_names_map

# ==========================================
# 4. 리포트 생성 (오류 수정됨)
# ==========================================
def main():
    # 1. GT 분석
    gt_counts, gt_total = analyze_ground_truth(TEST_LABEL_DIR)

    # 2. Prediction 분석
    pred_counts, pred_scores, pred_total, model_names = analyze_predictions(BEST_MODEL_PATH, TEST_IMG_DIR)

    print("\n" + "="*80)
    print("📊 [분석 리포트] 원본(GT) vs 예측(Prediction)")
    print("="*80)

    # [섹션 1] 수량 비교
    print("\n[1. 클래스별 검출 수량 비교]")
    print(f"{'Class':<20} {'GT Count':<10} {'Pred Count':<10} {'Diff':<10} {'Status'}")
    print("-" * 80)

    all_keys = set(gt_counts.keys()) | set(pred_counts.keys())
    sorted_keys = sorted(list(all_keys), key=lambda x: str(x))

    for key in sorted_keys:
        gt_n = gt_counts[key]

        # 매핑 로직
        if key in pred_counts:
            pred_n = pred_counts[key]
        elif isinstance(key, str):
            pred_n = pred_counts.get(key, 0)
        else:
            pred_n = pred_counts[key]

        display_name = str(key)
        if isinstance(key, int) and key in model_names:
            display_name = f"{key} ({model_names[key]})"

        diff = pred_n - gt_n

        if gt_n == 0: status = "New Detect"
        elif pred_n == 0: status = "Missed"
        elif diff > 0: status = f"Over (+{diff})"
        elif diff < 0: status = f"Under ({diff})"
        else: status = "Match"

        print(f"{display_name[:20]:<20} {gt_n:<10,} {pred_n:<10,} {diff:<10,} {status}")

    print("-" * 80)
    print(f"{'TOTAL':<20} {gt_total:<10,} {pred_total:<10,} {pred_total-gt_total:<10,} -")

    # [섹션 2] 분포 분석 (오류 수정 파트)
    print("\n\n[2. 예측값 신뢰도(Confidence) 분포 분석]")
    if pred_total > 0:
        df = pd.DataFrame({'score': pred_scores})
        df['score_100'] = df['score'] * 100

        # 🛠️ [수정됨] bins 개수 = 11개, labels 개수 = 10개로 정확히 맞춤
        # 0, 10, ..., 90, 101 (마지막에 101을 써서 100점 포함 보장)
        bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 101]
        labels = ['0~9', '10~19', '20~29', '30~39', '40~49', '50~59', '60~69', '70~79', '80~89', '90~100']

        # right=False: [0, 10) -> 0이상 10미만. 마지막 구간은 101 덕분에 100 포함.
        try:
            df['range'] = pd.cut(df['score_100'], bins=bins, labels=labels, right=False)

            dist_df = df.groupby('range', observed=False).size().reset_index(name='Count')
            dist_df['Ratio(%)'] = (dist_df['Count'] / pred_total * 100).round(2)

            print(dist_df.to_string(index=False, justify='center'))
        except Exception as e:
            print(f"⚠️ 분포 생성 중 오류 발생: {e}")
            print(f"데이터 범위: {df['score_100'].min()} ~ {df['score_100'].max()}")
    else:
        print("탐지된 객체가 없어 분포를 그릴 수 없습니다.")

    print("="*80)

if __name__ == "__main__":
    main()

"""## 5-6. Visual Debugging
 - Human-in-the-loop: 수치(mAP)는 "얼마나 틀렸는지"는 알려주지만, "어떻게 틀렸는지"는 알려주지 않음
 - 사람의 눈으로 경계선 침범(Boundary Bleeding), 미탐지(False Negative), 오탐지(False Positive) 유형을 분류
"""

import os
import glob
import random
import cv2
import numpy as np
import matplotlib.pyplot as plt
from ultralytics import YOLO

# ======================================================================================
# 1. 설정 (경로 확인 필수)
# ======================================================================================
DATASET_ROOT = '/content/dataset/balanced_dataset_split_polygon'
PROJECT_ROOT = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION"
BEST_MODEL_PATH = os.path.join(PROJECT_ROOT, "FINE_TUNING_MODEL", "yolov8x_car_parts_seg", "weights", "best.pt")

# 클래스 이름 (ID 매핑용)
class_names = [
    "Front fender(L)", "Rear bumper", "Front Wheel(R)", "Trunk lid", "Rocker panel(L)",
    "Front fender(R)", "Front bumper", "Bonnet", "Rear Wheel(R)", "Rear door(R)",
    "Front door(R)", "Head lights(R)", "Rear fender(R)", "Rear fender(L)", "Rocker panel(R)",
    "Rear lamp(L)", "Side mirror(R)", "Rear Wheel(L)", "Rear door(L)", "Side mirror(L)",
    "Head lights(L)", "Front Wheel(L)", "Front door(L)", "Rear lamp(R)", "Windshield",
    "Roof", "Undercarriage", "Rear windshield", "C pillar(L)", "A pillar(L)",
    "C pillar(R)", "A pillar(R)"
]

# ======================================================================================
# 2. 모델 로드
# ======================================================================================
if os.path.exists(BEST_MODEL_PATH):
    model = YOLO(BEST_MODEL_PATH)
    print(f"✅ 모델 로드 완료: {os.path.basename(BEST_MODEL_PATH)}")
else:
    print("⚠️ 모델 파일이 없습니다. (시각화 기능만 테스트하려면 더미 모델 필요)")
    model = None

# ======================================================================================
# 3. Ground Truth (정답) 로드 함수
# ======================================================================================
def get_ground_truth_mask(img_path, lbl_path, img_shape, class_names):
    h, w = img_shape[:2]
    gt_overlay = np.zeros((h, w, 3), dtype=np.uint8) # 빈 검정 이미지

    gt_polygons = []
    gt_labels = []

    if os.path.exists(lbl_path):
        with open(lbl_path, 'r') as f:
            for line in f:
                parts = list(map(float, line.strip().split()))
                cls_id = int(parts[0])
                coords = parts[1:]

                # 좌표 복원
                pts = []
                for i in range(0, len(coords), 2):
                    pts.append([int(coords[i] * w), int(coords[i+1] * h)])
                pts = np.array(pts, np.int32).reshape((-1, 1, 2))

                gt_polygons.append(pts)
                name = class_names[cls_id] if cls_id < len(class_names) else str(cls_id)
                gt_labels.append(name)

    return gt_polygons, gt_labels

# ======================================================================================
# 4. 비교 시각화 실행 (Visual Debugging)
# ======================================================================================
def visual_debug(num_samples=3, conf_threshold=0.25):
    test_img_dir = os.path.join(DATASET_ROOT, 'test', 'images')
    test_lbl_dir = os.path.join(DATASET_ROOT, 'test', 'labels')

    img_files = glob.glob(os.path.join(test_img_dir, '*.*'))
    if not img_files:
        print("❌ Test 이미지가 없습니다.")
        return

    # 랜덤 샘플링
    samples = random.sample(img_files, min(num_samples, len(img_files)))

    print(f"📸 Visual Debugging 시작 (Confidence Threshold: {conf_threshold})")
    print("-" * 60)

    for i, img_path in enumerate(samples):
        file_name = os.path.splitext(os.path.basename(img_path))[0]
        lbl_path = os.path.join(test_lbl_dir, file_name + '.txt')

        # 1. 이미지 로드
        origin_img = cv2.imread(img_path)
        origin_img = cv2.cvtColor(origin_img, cv2.COLOR_BGR2RGB)
        h, w, _ = origin_img.shape

        # 2. Ground Truth (정답) 시각화 생성
        gt_img = origin_img.copy()
        gt_polys, gt_names = get_ground_truth_mask(img_path, lbl_path, origin_img.shape, class_names)

        for pts, label in zip(gt_polys, gt_names):
            color = (0, 255, 0) # 정답은 항상 초록색 테두리
            cv2.polylines(gt_img, [pts], True, color, 2)
            # 내부 살짝 색칠
            overlay = gt_img.copy()
            cv2.fillPoly(overlay, [pts], color)
            cv2.addWeighted(overlay, 0.3, gt_img, 0.7, 0, gt_img)
            # 라벨 텍스트
            cv2.putText(gt_img, label, (pts[0][0][0], pts[0][0][1]-5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)

        # 3. Prediction (예측) 실행 및 시각화
        pred_img = origin_img.copy()
        if model:
            results = model.predict(img_path, conf=conf_threshold, verbose=False)
            result = results[0]

            # [수정] alpha 파라미터 제거
            # line_width와 font_size만 사용하여 렌더링
            pred_plot = result.plot(line_width=2, font_size=1.0)
            pred_img = cv2.cvtColor(pred_plot, cv2.COLOR_BGR2RGB) # RGB 변환

        # 4. 나란히 비교 (Left: GT, Right: Pred)
        fig, axes = plt.subplots(1, 2, figsize=(18, 9))

        axes[0].imshow(gt_img)
        axes[0].set_title(f"[Ground Truth] Correct Labels\n(File: {file_name})", fontsize=14, fontweight='bold', color='green')
        axes[0].axis('off')

        axes[1].imshow(pred_img)
        axes[1].set_title(f"[Prediction] Model Output\n(Conf > {conf_threshold})", fontsize=14, fontweight='bold', color='blue')
        axes[1].axis('off')

        plt.tight_layout()
        plt.show()

        print(f"✅ Sample {i+1} 분석 완료.")

visual_debug(num_samples=3, conf_threshold=0.25)

"""#### 오탐건 위주"""

import os
import glob
import random
import cv2
import numpy as np
import matplotlib.pyplot as plt
from ultralytics import YOLO

# ======================================================================================
# 1. 설정 및 타겟 클래스 지정
# ======================================================================================
DATASET_ROOT = '/content/dataset/balanced_dataset_split_polygon'
PROJECT_ROOT = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION"
BEST_MODEL_PATH = os.path.join(PROJECT_ROOT, "FINE_TUNING_MODEL", "yolov8x_car_parts_seg", "weights", "best.pt")

class_names = [
    "Front fender(L)", "Rear bumper", "Front Wheel(R)", "Trunk lid", "Rocker panel(L)",
    "Front fender(R)", "Front bumper", "Bonnet", "Rear Wheel(R)", "Rear door(R)",
    "Front door(R)", "Head lights(R)", "Rear fender(R)", "Rear fender(L)", "Rocker panel(R)",
    "Rear lamp(L)", "Side mirror(R)", "Rear Wheel(L)", "Rear door(L)", "Side mirror(L)",
    "Head lights(L)", "Front Wheel(L)", "Front door(L)", "Rear lamp(R)", "Windshield",
    "Roof", "Undercarriage", "Rear windshield", "C pillar(L)", "A pillar(L)",
    "C pillar(R)", "A pillar(R)"
]

# 집중 분석할 타겟 클래스 (성능 낮은 것들)
target_classes = [
    "Rear lamp(L)",  "Rocker panel(L)",
    "Rear windshield", "Windshield", "C pillar(L)", "Roof"
]

# ======================================================================================
# 2. 유틸리티 함수 (이미지 필터링 및 GT 파싱)
# ======================================================================================
def get_ground_truth_mask(lbl_path, img_shape, class_names):
    h, w = img_shape[:2]
    gt_polygons, gt_labels = [], []
    if os.path.exists(lbl_path):
        with open(lbl_path, 'r') as f:
            for line in f:
                parts = list(map(float, line.strip().split()))
                cls_id = int(parts[0])
                coords = parts[1:]
                pts = []
                for i in range(0, len(coords), 2):
                    pts.append([int(coords[i] * w), int(coords[i+1] * h)])
                pts = np.array(pts, np.int32).reshape((-1, 1, 2))
                gt_polygons.append(pts)
                name = class_names[cls_id] if cls_id < len(class_names) else str(cls_id)
                gt_labels.append(name)
    return gt_polygons, gt_labels

def find_images_with_targets(target_names, split='test'):
    label_dir = os.path.join(DATASET_ROOT, split, 'labels')
    image_dir = os.path.join(DATASET_ROOT, split, 'images')
    target_ids = [class_names.index(name) for name in target_names if name in class_names]
    found_images = []

    # 빠른 검색을 위해 glob 사용
    all_labels = glob.glob(os.path.join(label_dir, '*.txt'))
    if not all_labels: return []

    print(f"🔍 '{split}' 셋에서 {target_names} 포함 이미지 검색 중...")
    for lbl_file in all_labels:
        try:
            with open(lbl_file, 'r') as f:
                content = f.read()
                # 텍스트 전체에서 ID 검색 (빠른 필터링)
                for tid in target_ids:
                    if f"{tid} " in content: # "ID " 형태로 검색
                        base_name = os.path.splitext(os.path.basename(lbl_file))[0]
                        for ext in ['.jpg', '.png', '.jpeg']:
                            img_path = os.path.join(image_dir, base_name + ext)
                            if os.path.exists(img_path):
                                found_images.append(img_path)
                                break
                        break # 이미 찾았으면 다음 파일로
        except: continue

    print(f"✅ 총 {len(found_images)}장의 관련 이미지를 찾았습니다.")
    return found_images

# ======================================================================================
# 3. 개선된 시각화 실행 (GT Overlay + 가시성 향상)
# ======================================================================================
def visual_debug_improved(num_samples=5, conf_threshold=0.25):
    # 1. 타겟 이미지만 필터링
    target_img_files = find_images_with_targets(target_classes)
    if not target_img_files:
        print("❌ 해당 클래스가 포함된 Test 이미지가 없습니다.")
        return

    # 2. 샘플링
    samples = random.sample(target_img_files, min(num_samples, len(target_img_files)))

    # 3. 모델 로드
    if os.path.exists(BEST_MODEL_PATH):
        model = YOLO(BEST_MODEL_PATH)
    else:
        model = None

    print(f"\n📸 Improved Visual Debugging (Targets: {target_classes})")
    print("-" * 60)

    for i, img_path in enumerate(samples):
        file_name = os.path.splitext(os.path.basename(img_path))[0]
        lbl_path = os.path.join(DATASET_ROOT, 'test', 'labels', file_name + '.txt')

        # 이미지 로드
        origin_img = cv2.imread(img_path)
        origin_img = cv2.cvtColor(origin_img, cv2.COLOR_BGR2RGB)

        # --- [Left] Ground Truth Visualization (개선됨) ---
        gt_img = origin_img.copy()
        gt_polys, gt_labels = get_ground_truth_mask(lbl_path, origin_img.shape, class_names)

        # 오버레이를 위한 별도 레이어
        overlay_layer = gt_img.copy()

        for pts, label in zip(gt_polys, gt_labels):
            is_target = label in target_classes

            if is_target:
                # 타겟 클래스: 빨간색 (Red)
                # (R, G, B) = (255, 0, 0)
                fill_color = (255, 0, 0)
                border_color = (255, 0, 0)
                thickness = 2 # 조금 얇게
            else:
                # 비타겟 클래스: 노란색 (Yellow) - 회색보다 눈에 잘 띔
                # (R, G, B) = (255, 255, 0)
                fill_color = (255, 255, 0)
                border_color = (255, 215, 0) # Gold에 가까운 색
                thickness = 1 # 아주 얇게

            # 1. 내부 채우기 (Overlay용)
            cv2.fillPoly(overlay_layer, [pts], fill_color)

            # 2. 외곽선 그리기 (원본 위에 선명하게)
            cv2.polylines(gt_img, [pts], True, border_color, thickness, cv2.LINE_AA)

            # 3. 텍스트 라벨 (가독성 위해 배경 박스 추가)
            if is_target: # 타겟만 텍스트 표시 (너무 복잡해지는 것 방지)
                text_pos = (pts[0][0][0], pts[0][0][1] - 5)
                # 텍스트 배경
                (w, h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
                cv2.rectangle(gt_img, (text_pos[0], text_pos[1] - h - 5), (text_pos[0] + w, text_pos[1] + 5), border_color, -1)
                # 텍스트
                cv2.putText(gt_img, label, text_pos, cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1, cv2.LINE_AA)

        # 투명도 적용하여 합치기 (GT Overlay 완성)
        # alpha=0.4 (Overlay), beta=0.6 (Original)
        cv2.addWeighted(overlay_layer, 0.4, gt_img, 0.6, 0, gt_img)

        # --- [Right] Prediction Visualization ---
        pred_img = origin_img.copy()
        if model:
            results = model.predict(img_path, conf=conf_threshold, verbose=False)
            result = results[0]
            pred_plot = result.plot(line_width=2, font_size=1.0)
            pred_img = cv2.cvtColor(pred_plot, cv2.COLOR_BGR2RGB)

        # 시각화
        fig, axes = plt.subplots(1, 2, figsize=(18, 9))

        axes[0].imshow(gt_img)
        axes[0].set_title(f"[Ground Truth] Red: Targets / Yellow: Others\n(Targets: {target_classes})", fontsize=12, fontweight='bold')
        axes[0].axis('off')

        axes[1].imshow(pred_img)
        axes[1].set_title(f"[Prediction] Model Output", fontsize=12, fontweight='bold')
        axes[1].axis('off')

        plt.tight_layout()
        plt.show()
        print(f"✅ Sample {i+1} 확인 완료 ({file_name})")

visual_debug_improved(num_samples=20, conf_threshold=0.25)

