# -*- coding: utf-8 -*-
"""2_study4_damage_part_classification_untet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZYiqRfETVO2fOPnp_KFI96X_X-9VKs3J
"""

### train시 1시간 정도 소모 됩니다. colab환경에서 아래를 browser의 console 에서 붙여 넣기가 필요할 수 있습니다.
### shift+cntr+i 로 browser console 열기
# https://github.com/chulminkw/DLCV/blob/master/data/util/colab_autoclick.js
'''
function ClickConnect(){
console.log("Working");
document.querySelector("colab-toolbar-button#connect").click()
}
setInterval(ClickConnect,60000)
'''

"""# step1. Colab 환경 설정 및 데이터 준비"

## 1-1. 라이브러리 설치 및 드라이브 마운트
"""

# 1-1. 필수 라이브러리 설치
!pip install segmentation-models-pytorch -q
!pip install albumentations -q

# 1-2. 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

import os
import shutil
import torch
import numpy as np
import cv2
import matplotlib.pyplot as plt
from glob import glob
from tqdm import tqdm

# GPU 설정
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"🚀 사용 장치: {device}")

"""# Step 2: 데이터 준비 및 변환 (YOLO Polygon -> U-Net Mask)
 - YOLO는 좌표(.txt)를 쓰지만, U-Net은 정답 이미지(Mask)가 필요합니다. 이 단계에서 라벨 형식을 변환합니다.
"""

# 2-1. 데이터셋 압축 해제 (YOLO와 동일)
drive_path = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION/balanced_dataset_split_polygon.zip"
local_zip_path = '/content/balanced_dataset_split_polygon.zip'
extract_path = '/content/dataset'

if not os.path.exists(extract_path):
    print("🚀 데이터셋 복사 및 압축 해제 중...")
    shutil.copy(drive_path, local_zip_path)
    !unzip -q {local_zip_path} -d {extract_path}
    print("✅ 압축 해제 완료!")
else:
    print("✅ 이미 데이터셋이 존재합니다.")

# 2-2. Polygon(.txt)을 Mask(.png)로 변환하는 함수
def create_masks(data_root):
    print("🔄 YOLO Polygon 라벨을 U-Net용 마스크 이미지로 변환합니다...")

    # 클래스 정보 로드 (없으면 기본값 설정 필요)
    # Background는 0번, 나머지 클래스는 1번부터 시작하도록 매핑

    for split in ['train', 'val', 'test']:
        img_dir = os.path.join(data_root, split, 'images')
        lbl_dir = os.path.join(data_root, split, 'labels')
        mask_dir = os.path.join(data_root, split, 'masks') # 마스크 저장 경로

        os.makedirs(mask_dir, exist_ok=True)

        img_files = glob(os.path.join(img_dir, '*.*'))

        for img_path in tqdm(img_files, desc=f"{split} converting"):
            # 이미지 크기 확인
            img = cv2.imread(img_path)
            if img is None: continue
            h, w = img.shape[:2]

            # 빈 마스크 생성 (0=배경)
            mask = np.zeros((h, w), dtype=np.uint8)

            # 라벨 파일 읽기
            basename = os.path.basename(img_path).rsplit('.', 1)[0]
            txt_path = os.path.join(lbl_dir, basename + '.txt')

            if os.path.exists(txt_path):
                with open(txt_path, 'r') as f:
                    lines = f.readlines()

                for line in lines:
                    parts = line.strip().split()
                    cls_id = int(parts[0])

                    # 좌표 파싱 및 복원
                    coords = np.array([float(x) for x in parts[1:]]).reshape(-1, 2)
                    coords[:, 0] *= w
                    coords[:, 1] *= h
                    coords = coords.astype(np.int32)

                    # 마스크 그리기 (클래스 ID + 1 값을 픽셀 값으로 사용)
                    # 예: YOLO Class 0 -> Mask Value 1 (배경 0과 구분)
                    cv2.fillPoly(mask, [coords], cls_id + 1)

            # 마스크 저장 (PNG)
            cv2.imwrite(os.path.join(mask_dir, basename + '.png'), mask)

DATASET_ROOT = '/content/dataset/balanced_dataset_split_polygon'
create_masks(DATASET_ROOT)
print("✅ 마스크 변환 완료!")

"""# Step 3. 데이터셋 클래스 및 로더 정의
 - PyTorch 학습을 위한 Custom Dataset을 정의합니다. U-Net은 입력 이미지 크기가 고정되어야 하므로 리사이징(Resizing)이 필수입니다.
"""

from torch.utils.data import Dataset, DataLoader
import albumentations as A
from albumentations.pytorch import ToTensorV2

class CarPartDataset(Dataset):
    def __init__(self, root_dir, split='train', transform=None):
        self.img_dir = os.path.join(root_dir, split, 'images')
        self.mask_dir = os.path.join(root_dir, split, 'masks')
        self.img_ids = [os.path.basename(f) for f in glob(os.path.join(self.img_dir, '*.*'))]
        self.transform = transform

    def __len__(self):
        return len(self.img_ids)

    def __getitem__(self, idx):
        img_name = self.img_ids[idx]
        img_path = os.path.join(self.img_dir, img_name)
        mask_name = img_name.rsplit('.', 1)[0] + '.png'
        mask_path = os.path.join(self.mask_dir, mask_name)

        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)

        if self.transform:
            augmented = self.transform(image=image, mask=mask)
            image = augmented['image']
            mask = augmented['mask']

        # 마스크는 long 타입이어야 함 (CrossEntropy용)
        return image, mask.long()

# 전처리 파이프라인 (512x512 리사이징 권장)
IMG_SIZE = 512
train_transform = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.HorizontalFlip(p=0.5),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

val_transform = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

# 데이터로더 생성
train_dataset = CarPartDataset(DATASET_ROOT, split='train', transform=train_transform)
val_dataset = CarPartDataset(DATASET_ROOT, split='val', transform=val_transform)

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False, num_workers=2)

print(f"📦 Train Data: {len(train_dataset)}, Val Data: {len(val_dataset)}")

"""# Step 4. 모델 정의 및 학습 (Training)
 - 가장 대중적인 U-Net 구조에 ResNet34 백본을 사용하여 모델을 생성하고 학습합니다.
"""

import os
import torch
import segmentation_models_pytorch as smp
from tqdm import tqdm

# =========================================================
# ⚙️ 구글 드라이브 저장 경로 설정 (YOLO와 동일한 구조)
# =========================================================
PROJECT_ROOT = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION"
SAVE_DIR = os.path.join(PROJECT_ROOT, "FINE_TUNING_MODEL")

# U-Net 전용 폴더 생성
UNET_SAVE_DIR = os.path.join(SAVE_DIR, "unet_car_parts")
if not os.path.exists(UNET_SAVE_DIR):
    os.makedirs(UNET_SAVE_DIR)
    print(f"📂 폴더 생성 완료: {UNET_SAVE_DIR}")

# 최종 저장될 파일 경로
save_path = os.path.join(UNET_SAVE_DIR, 'best_unet_model.pth')
print(f"📍 모델이 저장될 경로: {save_path}")

# =========================================================
# 1. 모델 설정
# =========================================================
# 클래스 수 계산
# DATASET_ROOT 변수는 이전 단계에서 정의되어 있어야 함
if 'DATASET_ROOT' not in locals():
    DATASET_ROOT = '/content/dataset/balanced_dataset_split_polygon'

CLASSES_PATH = os.path.join(DATASET_ROOT, 'train', 'labels', 'classes.txt')
if os.path.exists(CLASSES_PATH):
    with open(CLASSES_PATH, 'r') as f:
        class_names = [line.strip() for line in f.readlines()]
    n_classes = len(class_names) + 1 # 배경(0) + 클래스
else:
    n_classes = 10 + 1 # 파일 없으면 임의 설정

print(f"🏗️ 모델 생성 (Classes: {n_classes} - 배경 포함)")

# U-Net 모델 생성
model = smp.Unet(
    encoder_name="resnet34",        # 인코더 백본
    encoder_weights="imagenet",     # 사전 학습 가중치
    in_channels=3,                  # 입력 채널 (RGB)
    classes=n_classes,              # 출력 채널 (클래스 수)
)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
model.to(device)

# 2. 손실함수 및 옵티마이저
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

# 3. 학습 루프
num_epochs = 20
best_loss = float('inf')

print(f"🔥 학습 시작... (총 {num_epochs} Epochs)")

for epoch in range(num_epochs):
    model.train()
    train_loss = 0

    # Train
    for images, masks in tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}"):
        images = images.to(device)
        masks = masks.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, masks)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    # Validation
    model.eval()
    val_loss = 0
    with torch.no_grad():
        for images, masks in val_loader:
            images = images.to(device)
            masks = masks.to(device)
            outputs = model(images)
            loss = criterion(outputs, masks)
            val_loss += loss.item()

    avg_train_loss = train_loss / len(train_loader)
    avg_val_loss = val_loss / len(val_loader)

    print(f"Epoch [{epoch+1}/{num_epochs}] Train Loss: {avg_train_loss:.4f}, Val Loss: {avg_val_loss:.4f}")

    # ★ 핵심: 성능이 좋아지면 구글 드라이브에 저장 ★
    if avg_val_loss < best_loss:
        best_loss = avg_val_loss
        torch.save(model.state_dict(), save_path)
        print(f"💾 Best Model Saved to Google Drive! ({avg_val_loss:.4f})")

print(f"\n✅ 모든 학습 완료. 최종 모델 위치:\n{save_path}")

"""# Step 5. 학습 결과 시각화 (Inference)
 - 학습된 모델을 사용하여 테스트 이미지의 분할 결과를 시각화합니다.
"""

import os
import glob
import random
import cv2
import numpy as np
import torch
import matplotlib.pyplot as plt
import segmentation_models_pytorch as smp
import albumentations as A
from albumentations.pytorch import ToTensorV2

# ======================================================================================
# 1. 설정 (경로 확인 필수)
# ======================================================================================
DATASET_ROOT = '/content/dataset/balanced_dataset_split_polygon'
PROJECT_ROOT = "/content/drive/MyDrive/03. HDMF/(pre_study)2026_HDMF_AUTO_SPOKE/SUBJECT/WEEK4_DAMAGE_PART_CLASSIFICATION"
# 저장해둔 U-Net 모델 경로
BEST_MODEL_PATH = os.path.join(PROJECT_ROOT, "FINE_TUNING_MODEL", "unet_car_parts", "best_unet_model.pth")

# 클래스 이름 (YOLO와 동일해야 함)
class_names = [
    "Front fender(L)", "Rear bumper", "Front Wheel(R)", "Trunk lid", "Rocker panel(L)",
    "Front fender(R)", "Front bumper", "Bonnet", "Rear Wheel(R)", "Rear door(R)",
    "Front door(R)", "Head lights(R)", "Rear fender(R)", "Rear fender(L)", "Rocker panel(R)",
    "Rear lamp(L)", "Side mirror(R)", "Rear Wheel(L)", "Rear door(L)", "Side mirror(L)",
    "Head lights(L)", "Front Wheel(L)", "Front door(L)", "Rear lamp(R)", "Windshield",
    "Roof", "Undercarriage", "Rear windshield", "C pillar(L)", "A pillar(L)",
    "C pillar(R)", "A pillar(R)"
]

# 클래스별 고유 색상 생성 (시각화용)
np.random.seed(42)
colors = np.random.randint(0, 255, size=(len(class_names) + 1, 3), dtype=np.uint8)

# ======================================================================================
# 2. U-Net 모델 로드
# ======================================================================================
device = 'cuda' if torch.cuda.is_available() else 'cpu'
n_classes = len(class_names) + 1  # 배경(0) 포함

# 모델 뼈대 생성 (학습 때와 동일한 설정이어야 함)
model = smp.Unet(
    encoder_name="resnet34",
    encoder_weights=None,
    in_channels=3,
    classes=n_classes
)

if os.path.exists(BEST_MODEL_PATH):
    print(f"🔄 모델 불러오는 중... {os.path.basename(BEST_MODEL_PATH)}")
    model.load_state_dict(torch.load(BEST_MODEL_PATH, map_location=device))
    model.to(device)
    model.eval()
    print("✅ U-Net 모델 로드 완료!")
else:
    print(f"❌ 모델 파일이 없습니다: {BEST_MODEL_PATH}")
    model = None

# ======================================================================================
# 3. Ground Truth 로드 함수 (YOLO 코드 재사용)
# ======================================================================================
# 정답은 .txt 파일(Polygon)을 읽어서 그리는 것이 가장 정확하므로 님의 코드를 그대로 씁니다.
def get_ground_truth_polygon(lbl_path, img_shape, class_names):
    h, w = img_shape[:2]
    gt_polygons = []
    gt_labels = []

    if os.path.exists(lbl_path):
        with open(lbl_path, 'r') as f:
            for line in f:
                parts = list(map(float, line.strip().split()))
                cls_id = int(parts[0])
                coords = parts[1:]

                # 좌표 복원
                pts = []
                for i in range(0, len(coords), 2):
                    pts.append([int(coords[i] * w), int(coords[i+1] * h)])
                pts = np.array(pts, np.int32).reshape((-1, 1, 2))

                gt_polygons.append(pts)
                name = class_names[cls_id] if cls_id < len(class_names) else str(cls_id)
                gt_labels.append(name)

    return gt_polygons, gt_labels

# ======================================================================================
# 4. U-Net 예측 및 시각화 함수
# ======================================================================================
# 전처리 (학습 때와 동일하게 512x512 리사이징)
val_transform = A.Compose([
    A.Resize(512, 512),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

def visual_debug_unet(num_samples=3):
    test_img_dir = os.path.join(DATASET_ROOT, 'test', 'images')
    test_lbl_dir = os.path.join(DATASET_ROOT, 'test', 'labels')

    img_files = glob.glob(os.path.join(test_img_dir, '*.*'))
    if not img_files:
        print("❌ Test 이미지가 없습니다.")
        return

    samples = random.sample(img_files, min(num_samples, len(img_files)))

    print(f"📸 U-Net Visual Debugging 시작")
    print("-" * 60)

    for i, img_path in enumerate(samples):
        file_name = os.path.splitext(os.path.basename(img_path))[0]
        lbl_path = os.path.join(test_lbl_dir, file_name + '.txt')

        # 1. 이미지 로드 (OpenCV)
        origin_img = cv2.imread(img_path)
        origin_img = cv2.cvtColor(origin_img, cv2.COLOR_BGR2RGB)
        h, w, _ = origin_img.shape

        # ---------------------------------------------------------
        # [Left] Ground Truth 시각화 (YOLO 코드 방식 유지)
        # ---------------------------------------------------------
        gt_img = origin_img.copy()
        gt_polys, gt_names = get_ground_truth_polygon(lbl_path, origin_img.shape, class_names)

        for pts, label in zip(gt_polys, gt_names):
            # 정답은 초록색 계열
            color = (0, 255, 0)
            cv2.polylines(gt_img, [pts], True, color, 2)

            # 내부 살짝 색칠
            overlay = gt_img.copy()
            cv2.fillPoly(overlay, [pts], color)
            cv2.addWeighted(overlay, 0.3, gt_img, 0.7, 0, gt_img)

            # 라벨 텍스트
            if len(pts) > 0:
                cv2.putText(gt_img, label, (pts[0][0][0], pts[0][0][1]-5),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)

        # ---------------------------------------------------------
        # [Right] U-Net Prediction 시각화
        # ---------------------------------------------------------
        pred_img = origin_img.copy()

        if model:
            # A. 전처리 (Resize -> Normalize -> Tensor)
            transformed = val_transform(image=origin_img)['image'].unsqueeze(0).to(device)

            # B. 추론
            with torch.no_grad():
                output = model(transformed)
                # (1, C, 512, 512) -> (512, 512) : 가장 높은 확률 클래스 선택
                pred_mask = torch.argmax(output, dim=1).squeeze().cpu().numpy()

            # C. 마스크를 원본 크기로 복원 (512 -> Original H, W)
            # interpolation=cv2.INTER_NEAREST 필수 (클래스 ID 유지를 위해)
            pred_mask_resized = cv2.resize(pred_mask.astype('uint8'), (w, h), interpolation=cv2.INTER_NEAREST)

            # D. 예측 마스크 오버레이 (Overlay)
            colored_mask = np.zeros_like(pred_img)

            # 배경(0)을 제외한 클래스만 색칠
            unique_classes = np.unique(pred_mask_resized)
            detected_labels = []

            for cls_id in unique_classes:
                if cls_id == 0: continue # 배경 제외

                # 해당 클래스 마스크 추출
                class_mask = (pred_mask_resized == cls_id).astype('uint8') * 255

                # 색상 지정
                color = colors[cls_id].tolist()

                # 마스크 영역에 색상 입히기
                colored_mask[pred_mask_resized == cls_id] = color

                # (옵션) 외곽선 그리기 - YOLO 스타일처럼 보이게
                contours, _ = cv2.findContours(class_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
                cv2.drawContours(pred_img, contours, -1, color, 2)

                # (옵션) 텍스트 표시 (가장 큰 덩어리 중심에)
                if len(contours) > 0:
                    largest_contour = max(contours, key=cv2.contourArea)
                    M = cv2.moments(largest_contour)
                    if M["m00"] != 0:
                        cX = int(M["m10"] / M["m00"])
                        cY = int(M["m01"] / M["m00"])
                        label_name = class_names[cls_id - 1] if (cls_id - 1) < len(class_names) else f"Class {cls_id}"
                        detected_labels.append(label_name)
                        cv2.putText(pred_img, label_name, (cX, cY),
                                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)

            # 이미지 합치기 (원본 + 컬러 마스크)
            cv2.addWeighted(colored_mask, 0.4, pred_img, 0.6, 0, pred_img)

        # ---------------------------------------------------------
        # 시각화 출력
        # ---------------------------------------------------------
        fig, axes = plt.subplots(1, 2, figsize=(18, 9))

        axes[0].imshow(gt_img)
        axes[0].set_title(f"[Ground Truth] Labels (Polygon)\n(File: {file_name})", fontsize=14, fontweight='bold', color='green')
        axes[0].axis('off')

        axes[1].imshow(pred_img)
        axes[1].set_title(f"[U-Net Prediction] Segmentation Mask", fontsize=14, fontweight='bold', color='blue')
        axes[1].axis('off')

        plt.tight_layout()
        plt.show()
        print(f"✅ Sample {i+1} 완료.")

# 실행
if __name__ == "__main__":
    visual_debug_unet(num_samples=3)

"""# Step 6. 모델 평가 (Evaluation - mIoU & Speed)
 - U-Net의 핵심 지표인 mIoU와 FPS를 측정합니다. sklearn을 활용해 정확한 mIoU를 계산합니다.
"""

from sklearn.metrics import jaccard_score
import time
from tqdm import tqdm
import pandas as pd

# =========================================================
# 📊 평가 함수 정의 (mIoU & FPS)
# =========================================================
def evaluate_unet_performance(model, dataloader, n_classes, device):
    model.eval()

    # 지표 변수
    iou_scores = []
    total_time = 0
    total_frames = 0

    print(f"🚀 성능 평가 시작 (총 {len(dataloader.dataset)}장)...")

    # Warm-up (GPU 예열)
    dummy = torch.randn(1, 3, 512, 512).to(device)
    for _ in range(5):
        _ = model(dummy)

    with torch.no_grad():
        for images, masks in tqdm(dataloader, desc="Evaluating"):
            images = images.to(device)
            # Flatten: mIoU 계산을 위해 1차원 배열로 펼침
            masks_np = masks.cpu().numpy().flatten()

            # 시간 측정 (Start)
            start_time = time.time()

            outputs = model(images)
            preds = torch.argmax(outputs, dim=1)

            # 시간 측정 (End)
            if device == 'cuda': torch.cuda.synchronize() # GPU 동기화 (정확한 시간 측정용)
            end_time = time.time()

            # 속도 누적
            total_time += (end_time - start_time)
            total_frames += images.size(0)

            # mIoU 계산 (Batch 단위)
            preds_np = preds.cpu().numpy().flatten()

            # micro: 전체 픽셀 합산 평균, macro: 클래스별 평균 (macro가 더 엄격함)
            # labels: 존재하는 클래스만 계산하거나 전체 클래스 지정
            current_iou = jaccard_score(masks_np, preds_np, average='macro', labels=list(range(n_classes)))
            iou_scores.append(current_iou)

    # 최종 계산
    final_miou = np.mean(iou_scores)
    fps = total_frames / total_time

    return final_miou, fps

# =========================================================
# ▶️ 실행 및 리포트 출력
# =========================================================
# DataLoader 생성 (Batch Size 1로 하면 FPS가 낮게 나올 수 있음, 8 권장)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False, num_workers=2)

# 평가 수행
miou, fps = evaluate_unet_performance(model, test_loader, n_classes, device)

# 결과 출력
print("\n" + "="*50)
print("📊 U-Net (ResNet34) Performance Report")
print("="*50)
print(f"📂 Model Path: {os.path.basename(load_path)}")
print(f"🖼️ Test Images: {len(test_dataset)}")
print("-" * 50)
print(f"🏆 Mean IoU (mIoU)  : {miou:.4f}")
print(f"⚡ Speed (FPS)      : {fps:.2f} frames/sec")
print("="*50)

# YOLO와 비교 가이드
print("\n[비교 가이드]")
print(f"1. YOLO mIoU가 {miou:.4f}보다 낮다면 -> 'U-Net이 정밀도(면적)는 더 우수함' 입증")
print(f"2. YOLO FPS가 {fps:.2f}보다 높다면 -> 'YOLO가 속도는 훨씬 빠름' 입증")

